import './globals.css'
import type { Metadata } from 'next'
import type { AppProps } from 'next/app'
import Nav from '@/components/nav';
import {berkeleyMono} from "@/components/font";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={berkeleyMono.className}>
      {children}
      </body>
    </html>
  )
}
